/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;
import javax.swing.JTextArea;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Willian
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextEditor = new javax.swing.JTextArea();

        jLabel3 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        MenuArquivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        ButtonLocalizar = new javax.swing.JMenuItem();
        ButtonSair = new javax.swing.JMenuItem();
        MenuSobre = new javax.swing.JMenu();
        ButtonSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editor de texto");

        TextEditor.setColumns(20);
        TextEditor.setLineWrap(true);
        TextEditor.setRows(5);
        TextEditor.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                System.out.println("Texto adicionado");
                Controller.getInstance().converterString(TextEditor.getText());
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                System.out.println("Texto removido");
                Controller.getInstance().apagar(TextEditor.getText());
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                System.out.println("Texto modificado");
                Controller.getInstance().converterString(TextEditor.getText());
            }
        });
        jScrollPane1.setViewportView(TextEditor);

        jLabel3.setText("Texto");

        MenuArquivo.setText("Arquivo");

        jMenuItem1.setText("Abrir texto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuArquivo.add(jMenuItem1);

        jMenuItem2.setText("Salvar texto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuArquivo.add(jMenuItem2);

        ButtonLocalizar.setText("Localizar");
        ButtonLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLocalizarActionPerformed(evt);
            }
        });
        MenuArquivo.add(ButtonLocalizar);

        ButtonSair.setText("Sair");
        ButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSairActionPerformed(evt);
            }
        });
        MenuArquivo.add(ButtonSair);

        Menu.add(MenuArquivo);

        MenuSobre.setText("Sobre");

        ButtonSobre.setText("Sobre");
        ButtonSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSobreActionPerformed(evt);
            }
        });
        MenuSobre.add(ButtonSobre);

        Menu.add(MenuSobre);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 589, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ButtonSairActionPerformed

    private void ButtonSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSobreActionPerformed
        // TODO add your handling code here:
        new Sobre().setVisible(true);
    }//GEN-LAST:event_ButtonSobreActionPerformed

    private void ButtonLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLocalizarActionPerformed
        // TODO add your handling code here:
        Localizar localizar = new Localizar();
        localizar.setVisible(true);
    }//GEN-LAST:event_ButtonLocalizarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new Abrir().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new Salvar().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);

            }
        });
    }

    public JTextArea getTextEditor() {
        return TextEditor;
    }

    public void setTextEditor(JTextArea TextEditor) {
        this.TextEditor = TextEditor;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ButtonLocalizar;
    private javax.swing.JMenuItem ButtonSair;
    private javax.swing.JMenuItem ButtonSobre;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MenuArquivo;
    private javax.swing.JMenu MenuSobre;
    private javax.swing.JTextArea TextEditor;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
